# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        args: ["check"]
      - id: prettier
        name: prettier
        entry: prettier --config frontend/.prettierrc.json --write --ignore-unknown
        language: node
        types_or: [javascript, jsx, ts, tsx, vue]
        additional_dependencies: ["prettier"]
      - id: eslint
        name: eslint
        language: node
        types_or: [javascript, jsx, ts, tsx, vue]
        entry: eslint -c frontend/.eslint.conf.js --fix
        additional_dependencies: ["eslint-plugin-vue", "eslint-config-prettier", "prettier", "eslint"]
  - repo: https://github.com/psf/black
    rev: "24.2.0"
    hooks:
      - id: black
